name: Django CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-20.04
    env: 
      AZURE_KEYVAULT_URL: ${{ secrets.AZURE_KEYVAULT_URL }}

    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        sudo apt-get install gettext
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        cd aussprachetrainer
        python manage.py test

    # Add any additional steps for deployment, etc.
